#Import library

In [ ]:
!pip uninstall numpy
!pip install numpy==1.26.4
!pip uninstall -y spacy
!pip install spacy==3.6.3
!pip install https://gitlab.com/trungtv/vi_spacy/-/raw/master/packages/vi_core_news_lg-3.6.0/dist/vi_core_news_lg-3.6.0.tar.gz
!pip install pyvi
#!pip install -U spacy
#!pip install --no-deps https://gitlab.com/trungtv/vi_spacy/-/raw/master/packages/vi_core_news_lg-3.6.0/dist/vi_core_news_lg-3.6.0.tar.gz
!python -m spacy validate

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Would remove:
    /usr/local/bin/f2py
    /usr/local/lib/python3.11/dist-packages/numpy-1.26.4.dist-info/*
    /usr/local/lib/python3.11/dist-packages/numpy.libs/libgfortran-040039e1.so.5.0.0
    /usr/local/lib/python3.11/dist-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so
    /usr/local/lib/python3.11/dist-packages/numpy.libs/libquadmath-96973f99.so.0.0.0
    /usr/local/lib/python3.11/dist-packages/numpy/*
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.26.4
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Found existing installation: spacy 3.6.1
Uninstalling spacy-3.6.1:
  Successfully uninstalled spacy-3.6.1
ERROR: Ignored the following yanked versions: 3.6.0.dev0, 3.7.3, 3.7.6, 3.8.0, 3.8.1, 4.0.0.dev1, 4.0.0.dev2
ERROR: Could not find a version th

In [ ]:
import requests
from bs4 import BeautifulSoup
import spacy
nlp = spacy.load('vi_core_news_lg')
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm
from sklearn.cluster import KMeans
from contextlib import nullcontext
import pandas as pd

#Crawl data

In [ ]:
def get_content(url, tage, attribute):
  page = requests.get(url)
  soup = BeautifulSoup(page.text, 'html.parser')
  web_dev = soup.find_all(tage, class_ = attribute)
  web_contents = [sen.text.strip() for sen in web_dev]
  return web_contents

In [ ]:
url = ['https://www.vinmec.com/vie/benh/benh-lao-phoi-3183',

       'https://thuvienphapluat.vn/phap-luat-doanh-nghiep/bai-viet/quy-dinh-moi-ve-tien-dien-tu-co-hieu-luc-tu-ngay-01-7-2024-7969.html#:~:text=C%C4%83n%20c%E1%BB%A9%20kho%E1%BA%A3n%2012%20%C4%90i%E1%BB%81u%203%20Ngh%E1%BB%8B%20%C4%91%E1%BB%8Bnh,to%C3%A1n%20cung%20%E1%BB%A9ng%20d%E1%BB%8Bch%20v%E1%BB%A5%20v%C3%AD%20%C4%91i%E1%BB%87n%20t%E1%BB%AD.',

       'https://rdsic.edu.vn/blog/toan/su-khac-nhau-giua-nguyen-phan-va-giam-phan-tong-quan-va-ung-dung-vi-cb.html']

corpus = []

content0 = get_content(url[0], 'div', 'item_detial_sick')
corpus.append(content0[1])
corpus.append(content0[4])

content1 = get_content(url[1], 'p', nullcontext)
corpus.append(content1[8])
corpus.append(content1[9])

content2 = get_content(url[2], 'p', nullcontext)
corpus.append(content2[4])
corpus.append(content2[5])

for i in range(len(corpus)):
  print(i)
  print(corpus[i])
  print('-----------------------------------------------------------------------')

0
Nguyên nhân bệnh Bệnh lao phổi

Bệnh lao là bệnh truyền nhiễm do vi khuẩn Mycobacterium tuberculosis gây ra. Bệnh lây lan do vi khuẩn lao phát tán ra ngoài khi người mắc lao phổi ho, nói, hắt hơi, khạc nhổ mà vô tình người tiếp xúc gần đó có thể bị hít vào và gây bệnh tại phổi. Từ phổi, vi khuẩn lao có thể qua đường máu hay bạch huyết đến các tạng khác trong cơ thể và gây bệnh tại đó.
Vi khuẩn lao có khả năng kháng lại cồn và axit mà ở nồng độ đó vi khuẩn khác bị tiêu diệt. Vi khuẩn lao tồn tại được nhiều tuần trong đờm, rác ẩm và tối, chết ở nhiệt độ 1000C/5 phút và dễ bị mất khả năng gây bệnh dưới ánh nắng mặt trời.
-----------------------------------------------------------------------
1
Đối tượng nguy cơ bệnh Bệnh lao phổi

Lao phổi là bệnh rất thường gặp, có thể ảnh hưởng mọi người trong mọi lứa tuổi.
Những yếu tố làm tăng nguy cơ mắc lao phổi bao gồm:

Suy giảm miễn dịch: nhiễm HIV, ung thư...
Tiếp xúc trực tiếp với nguồn lây, đặc biệt trẻ em
Bị các bệnh mạn tính: loét dạ dày t

In [ ]:
for i in range(len(corpus)):
  corpus[i] = corpus[i].split('.')[0]

for _ in corpus:
  print(_)
  print('-------------------')

Nguyên nhân bệnh Bệnh lao phổi

Bệnh lao là bệnh truyền nhiễm do vi khuẩn Mycobacterium tuberculosis gây ra
-------------------
Đối tượng nguy cơ bệnh Bệnh lao phổi

Lao phổi là bệnh rất thường gặp, có thể ảnh hưởng mọi người trong mọi lứa tuổi
-------------------
- Tiền điện tử được lưu trữ bằng ví điện tử hoặc thẻ trả trước
-------------------
- Ngân hàng, chi nhánh ngân hàng nước ngoài được phát hành, cung ứng ví điện tử, thẻ trả trước
-------------------
Nguyên phân là quá trình phân bào tạo ra hai tế bào con có bộ nhiễm sắc thể (NST) giống hệt tế bào mẹ
-------------------
Giảm phân là quá trình phân bào tạo ra bốn tế bào con có bộ NST giảm đi một nửa so với tế bào mẹ
-------------------


# Pre-processing

In [ ]:
print(spacy.__name__, spacy.__version__)

spacy 3.6.1


compare before and after pre-processing

In [ ]:
temp = [t.text for t in nlp(corpus[0])]
print(temp)

temp = [t.lower_ for t in nlp(corpus[0]) if not t.is_punct and not t.is_space]
print(temp)

print(len(temp))

['Nguyên nhân', 'bệnh', 'Bệnh', 'lao phổi', '\n\n', 'Bệnh', 'lao', 'là', 'bệnh', 'truyền nhiễm', 'do', 'vi khuẩn', 'Mycobacterium', 'tuberculosis', 'gây', 'ra']
['nguyên nhân', 'bệnh', 'bệnh', 'lao phổi', 'bệnh', 'lao', 'là', 'bệnh', 'truyền nhiễm', 'do', 'vi khuẩn', 'mycobacterium', 'tuberculosis', 'gây', 'ra']
15


the corpus after pre-procesing look like

In [ ]:
num_token = 0

pre_pro_corpus = []

for i in corpus:
  temp = [t.lower_ for t in nlp(i) if not t.is_punct and not t.is_space]
  pre_pro_corpus.append(temp)
  num_token += len(temp)
  print(len(temp))
  print(temp)

df = pd.DataFrame(pre_pro_corpus)

print('\ntotal: ', num_token)

15
['nguyên nhân', 'bệnh', 'bệnh', 'lao phổi', 'bệnh', 'lao', 'là', 'bệnh', 'truyền nhiễm', 'do', 'vi khuẩn', 'mycobacterium', 'tuberculosis', 'gây', 'ra']
19
['đối tượng', 'nguy cơ', 'bệnh', 'bệnh', 'lao phổi', 'lao phổi', 'là', 'bệnh', 'rất', 'thường', 'gặp', 'có thể', 'ảnh hưởng', 'mọi', 'người', 'trong', 'mọi', 'lứa', 'tuổi']
11
['tiền', 'điện tử', 'được', 'lưu trữ', 'bằng', 'ví', 'điện tử', 'hoặc', 'thẻ', 'trả', 'trước']
12
['ngân hàng', 'chi nhánh', 'ngân hàng', 'nước ngoài', 'được', 'phát hành', 'cung ứng', 'ví', 'điện tử', 'thẻ', 'trả', 'trước']
18
['nguyên phân', 'là', 'quá trình', 'phân', 'bào', 'tạo', 'ra', 'hai', 'tế bào', 'con', 'có', 'bộ', 'nhiễm', 'sắc thể', 'nst', 'giống hệt', 'tế bào', 'mẹ']
21
['giảm phân', 'là', 'quá trình', 'phân', 'bào', 'tạo', 'ra', 'bốn', 'tế bào', 'con', 'có', 'bộ', 'nst', 'giảm', 'đi', 'một', 'nửa', 'so', 'với', 'tế bào', 'mẹ']

total:  96


In [ ]:
unwanted_pipes = ["parser"]

def custom_tokenizer(doc):
    with nlp.disable_pipes(*unwanted_pipes):
        return [t.lower_ for t in nlp(doc) if not t.is_punct and not t.is_space]

#Vectorizer

In [ ]:
vectorizer = TfidfVectorizer(tokenizer = custom_tokenizer)

x_train = vectorizer.fit_transform(corpus)

print(x_train.shape)

print('\n', x_train)

(6, 61)

 <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 84 stored elements and shape (6, 61)>
  Coords	Values
  (0, 28)	0.22215393142137932
  (0, 2)	0.7286776068862983
  (0, 18)	0.1821694017215746
  (0, 17)	0.22215393142137932
  (0, 19)	0.13179485181223
  (0, 46)	0.22215393142137932
  (0, 10)	0.22215393142137932
  (0, 53)	0.22215393142137932
  (0, 22)	0.22215393142137932
  (0, 49)	0.22215393142137932
  (0, 13)	0.22215393142137932
  (0, 38)	0.15379992642018553
  (1, 2)	0.5011792531435386
  (1, 18)	0.3341195020956924
  (1, 19)	0.1208634102382922
  (1, 59)	0.2037278496104353
  (1, 26)	0.2037278496104353
  (1, 39)	0.2037278496104353
  (1, 42)	0.2037278496104353
  (1, 14)	0.2037278496104353
  (1, 9)	0.2037278496104353
  (1, 60)	0.2037278496104353
  (1, 24)	0.4074556992208706
  (1, 30)	0.2037278496104353
  (1, 45)	0.2037278496104353
  :	:
  (4, 4)	0.20132507317178566
  (4, 31)	0.24551409883404243
  (4, 41)	0.24551409883404243
  (4, 32)	0.20132507317178566
  (4, 12)	0.24551409

/usr/local/lib/python3.11/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [ ]:
print(x_train.toarray())

[[0.         0.         0.72867761 0.         0.         0.
  0.         0.         0.         0.         0.22215393 0.
  0.         0.22215393 0.         0.         0.         0.22215393
  0.1821694  0.13179485 0.         0.         0.22215393 0.
  0.         0.         0.         0.         0.22215393 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.15379993 0.         0.         0.
  0.         0.         0.         0.         0.22215393 0.
  0.         0.22215393 0.         0.         0.         0.22215393
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.50117925 0.         0.         0.
  0.         0.         0.         0.20372785 0.         0.
  0.         0.         0.20372785 0.         0.         0.
  0.3341195  0.12086341 0.         0.20372785 0.         0.
  0.4074557  0.         0.20372785 0.         0.         0.
  0.20372785 0.         0.         0.         0.         0.
  0.      

In [ ]:
test = [
    'Bệnh lao (còn gọi là TB) là một bệnh truyền nhiễm',
    'Lao phổi rất nguy hiểm',
    'mẹ lây bệnh sang con',
    'mẹ mua thiết bị điện tử giúp trị bệnh cho con',
    'Tiền điện tử rất tiện lợi',
    'Tiền điện tử là tiền được lưu trên các phương tiện điện tử',
    'Ví điện tử có thể do ngân hàng phát hành',
    'Nguyên phân là gì',
    'giảm phân sinh ra nhiều tế bào hơn nguyên phân',
    'Đều là quá trình phân chia tế bào'
]

x_test = vectorizer.transform(test)

print(x_test.shape)

print('\n', x_test)

(10, 61)

 <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 38 stored elements and shape (10, 61)>
  Coords	Values
  (0, 2)	0.6155993138425042
  (0, 17)	0.37535888699748476
  (0, 19)	0.4453701860841903
  (0, 25)	0.37535888699748476
  (0, 46)	0.37535888699748476
  (1, 18)	0.6340862024337309
  (1, 39)	0.7732623667832087
  (2, 2)	0.5773502691896257
  (2, 6)	0.5773502691896257
  (2, 23)	0.5773502691896257
  (3, 2)	0.5
  (3, 6)	0.5
  (3, 23)	0.5
  (3, 57)	0.5
  (4, 39)	0.6117125098631682
  (4, 44)	0.6117125098631682
  (4, 57)	0.501613008756558
  (5, 19)	0.2136006403948891
  (5, 44)	0.7200921942756119
  (5, 57)	0.5904859003676398
  (5, 58)	0.2952429501838199
  (6, 9)	0.43254606386088906
  (6, 10)	0.43254606386088906
  (6, 29)	0.43254606386088906
  (6, 35)	0.43254606386088906
  (6, 54)	0.35469396002314924
  (6, 57)	0.35469396002314924
  (7, 19)	0.4169638817420929
  (7, 27)	0.702835993333765
  (7, 36)	0.5763355687419489
  (8, 11)	0.41375286502959013
  (8, 27)	0.41375286502959013
 

In [ ]:
print(x_test.toarray())

[[0.         0.         0.61559931 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.37535889
  0.         0.44537019 0.         0.         0.         0.
  0.         0.37535889 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.37535889 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.6340862  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.   

# Classification with SVM

###Training

In [ ]:
y_train = [
    'Lao phoi',
    'Lao phoi',
    'Tien dien tu',
    'Tien dien tu',
    'Phan chia te bao',
    'Phan chia te bao',
]

clf = svm.SVC(kernel = 'linear')
clf.fit(x_train, y_train)

SVC(kernel='linear')

###Prediction

In [ ]:
y_test = clf.predict(x_test)

print(y_test)

['Lao phoi' 'Lao phoi' 'Lao phoi' 'Lao phoi' 'Tien dien tu' 'Tien dien tu'
 'Tien dien tu' 'Phan chia te bao' 'Phan chia te bao' 'Phan chia te bao']


# Classification with Kmean

###Training

In [ ]:
Kmean = KMeans(n_clusters = 3, n_init = 10, random_state = 42)

Kmean.fit_transform(x_train.toarray())

array([[1.30919074, 1.31191397, 0.52820752],
       [1.30919074, 1.33160188, 0.52820752],
       [0.53480801, 1.34394918, 1.31186768],
       [0.53480801, 1.34394918, 1.31186768],
       [1.30919074, 0.4402279 , 1.28765465],
       [1.30919074, 0.4402279 , 1.29066733]])

In [ ]:
y_train = Kmean.labels_

print(y_train)

[2 2 0 0 1 1]


In [ ]:
y_test = Kmean.predict(x_test.toarray())

print(y_test)

[2 2 2 2 0 0 0 1 1 1]


# Cả 2 mô hình phân loại đều cho ra kết quả giống nhau